version: '3.0'

services:
  webserver:
    container_name: PHP-web
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - .:/app
      - .nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

  app:
    container_name: PHP-app
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/app
