version: '3.0'


services:
  webserver:
    container_name: thirdProject-web
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - .:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80


  app:
    container_name: thirdProject-app
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - .:/app
